---
title: "Setup instructions"
---

Prior to the workshop check you have the required software and set up any accounts you might need for publishing your dashboard.

## Software

You will be able to follow along with this workshop in R or in Python.
See the required software suite for each language below.

### R

-   [R](https://cran.r-project.org): 4.4.1

-   [Quarto](https://quarto.org/docs/download/): v1.5

-   [RStudio](https://posit.co/download/rstudio-desktop/): 2024.04.2+764

-   Packages:

```{r}
#| eval: false

pkg_list <- c(
  "tidyverse", "gt", "ggthemes", "DT", "here", "paletteer"
)
install.packages(pkg_list)
```

### Python

-   [Python](https://www.python.org/downloads/): 3
-   [Quarto](https://quarto.org/docs/download/): v1.5
-   [VS Code](https://code.visualstudio.com/download) as well as the [VS Code Quarto Extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto) and [VS Code Jupyter Extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
-   Packages: We recommend `pip install`ing the following packages. If you have a different preferred way of managing your environment, you’re welcomed to do so. Just make sure you have these packages installed in order to be able to follow along with the examples.

```         
great_tables==0.10.0
ipykernel==6.29.5
jupyter==1.0.0
pandas==2.2.2
plotnine==0.13.6
```

## Publishing accounts

You do not need to publish your dashboard during the workshop, but it would be good practice!

To publish your website you'll need an account on one of Quarto's publishing venues:

-   **(Recommended)** [Quarto Pub](https://quartopub.com/sign-up)
-   [GitHub](https://github.com) only **if you are already** a Git/GitHub user

## Discord

We're not going to be making heavy use of Discord during the workshop, but it's a great place to share code snippets for questions that come up or (inevitable) typos that need to be fixed.

More importantly, it's a great place to connect with other conference attendees.

-   [pos.it/conf-event-portal](http://pos.it/conf-event-portal) \> Login
-   Click on "Join Discord, the virtual networking platform!"
-   Browse Channels -\> #workshop-quarto-dashboards
